package com.example.masterdegree;

public class Constants {
    public static final String CANAL_PLUS = "Canal+";
    public static final String CYFROWY_POLSAT = "Cyfrowy polsat";
    public static final String CANAL_PLUS_ID = "5e77b71972e086126cc4e6b3";
    public static final String CYFROWY_POLSAT_ID = "5e77b70072e086126cc4e6b2";
    public static final String CANAL_PLUS_START = "START+";
    public static final String ELEVEN_SPORTS = "Eleven Sports";
    public static final String FUN = "Fun";
    public static final String CANAL_PLUS_SUPERPREMIUM = "Superpemium+ 4K";
    public static final String FAMILY_SMALL_CYFROWY_POLSAT = "Familijny small";
    public static final String SMALL_FAMILY_CYFROWY_POLSAT = "Familijny small";
    public static final String FAMILY_CYFROWY_POLSAT = "Familijny Max HD + Cinemax HD + Film HD + Sport HD";
    public static final String FOX_PLAY = "FOX_PLAY";
    public static final String ELEVEN_SPORTS_1 = ELEVEN_SPORTS + "1";
    public static final String ELEVEN_SPORTS_2 = ELEVEN_SPORTS + "2";
    public static final String MULTI_MAN_PACK =  "Multi man pack";
    public static final String FUN_TV =  "4fun TV";
    public static final String FUN_DANCE =  "4fun Dance";
    public static final String FUN_GOLD_HTS =  "4fun Gold Hits";
    public static final String ACTIVE_FAMILY =  "Active Family";
    public static final String AMC =  "AMC HD";
    public static final String ANIMAL_PLANET_HD =  "Animal Planet HD";
    public static final String ALE_KINO_HD =  "Ale Kino+ HD";
    public static final String AIRGANG_TV =  "Arirang TV";
    public static final String ATM =  "ATM Rozrywka";
    public static final String BBC =  "BBC World News";
    public static final String HBO =  "HBO";
    public static final String HBO_2 =  HBO + "2";
    public static final String HBO3 =  HBO + "3";
    public static final String HBO_GO =  HBO + " GO";
    public static final String DORCEL =  "Dorcel TV";
    public static final String BLUR_HUSTLER =  "blur Hustler";
    public static final String HUSTLER_HD =  "Hustler HD";
    public static final String FIGHTBOX =  "Fightbox";
    public static final String HISTORY =  "History";
    public static final String HISTORY2 =  HISTORY + "2";
    public static final String ADVENTURE =  "Adventure";
    public static final String ATM_ROZRYWKA =  "ATM Rozrywka HD";
    public static final String POLSAT =  "Polsat";
    public static final String TVN =  "Tvn";
    public static final String BRAZZERS =  "Brazzers";
    public static final String PRIVATE_HD =  "Private hd";
    public static final String VIVD_HD =  "Vivd hd";
    public static final String SPORT_PREMIUM1 =  "Sport premium 1";
    public static final String SPORT_PREMIUM2 =  "Sport premium 2";
    public static final String POLSAT_SPORT_PREMIUM =  "Polsat sport premium";

}
