export const DEFAULT_MIN_PRICE_FILTER_VALUE = 78.00;
export const DEFAULT_MAX_PRICE_FILTER_VALUE = 200.00;
export const MAX_PRICE_FILTER_VALUE = 400.00;
export const MIN_PRICE_FILTER_VALUE = 0.00;
export const NUMBER_OF_MONTHS_VALUE_1 = 12;
export const NUMBER_OF_MONTHS_VALUE_2 = 15;
export const NUMBER_OF_MONTHS_VALUE_3 = 24;
